### ISSUE TITLE
Show metadata on historic gps data

### ISSUE THREAD

**Issue by jhn-nordic** [bifravst/app#694]
It would be nice to see metadata like time, speed, when hoovering over og pushing the "dots" in the gps historic data.

From a developer/integrator point of view it would also be interesting to see if there was cell coverage at the point where the gps location was aquired. (i.e show link quality or if the data was a part of a batch send(which often will indicate that it was out of coverage))

**Comment by coderbyheart** [comment]
> It would be nice to see metadata like time, speed, when hoovering over og pushing the "dots" in the gps historic data.

That should be pretty straightforward to implement, because we send this information already in the GPS object:
https://github.com/bifravst/bifravst/blob/b5327fbe0a14e72171ce201c11d5d6465fa6040b/docs/firmware/state.reported.aws.json#L21-L31

So it needs changes to the Map component of the app to show clickable markers instead of only dots (as it does now). This would be very similar to the [Thingy World Map](https://ew20.world.thingy.rocks/), which has icons with extra labels and displays tool-tips on click.

> From a developer/integrator point of view it would also be interesting to see if there was cell coverage at the point where the gps location was aquired. (i.e show link quality or if the data was a part of a batch send(which often will indicate that it was out of coverage))

Right now the batch messages are *unwrapped* and the processed as regular messages, there is no tracking whether a sensor messages came from a batch. But this would also be pretty straight forward to implement. However before adding this to Aurora, I will look into https://github.com/bifravst/aws/issues/394 first.

**Comment by coderbyheart** [comment]
I've started this. The batch and RSRP info is not yet there, but the rest of the location data is now shown in a tooltip when clicking on a circle for one of the historical positions:

![Screenshot_20201202_165901](https://user-images.githubusercontent.com/188915/100898835-74551e80-34c1-11eb-9957-a06c90e90d30.png)

**Comment by coderbyheart** [comment]
The map now shows the roaming information entry that is older, but closest (in time) to the historical position. 

![image](https://user-images.githubusercontent.com/188915/101187355-8a471880-3654-11eb-83a4-0cfd66cae018.png)

**Comment by coderbyheart** [comment]
Positions contained in a batch update are now marked with a red circle, and do not have the connection information attached.

![20201207T155150](https://user-images.githubusercontent.com/188915/101365661-5cf0a980-38a4-11eb-9d04-2fc937e3f230.png)
